packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@vercel/python@6.55.2'
  - '@vercel/vc-native-darwin-arm64@58.7.1'
  - '@vercel/vc-native-darwin-x64@58.7.1'
  - '@vercel/vc-native-linux-arm64@58.7.1'
  - '@vercel/vc-native-linux-x64@58.7.1'
  - bumpp@12.2.0
  - vercel@58.7.1
