packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@cspell/cspell-bundled-dicts@10.3.3'
  - '@cspell/cspell-json-reporter@10.3.3'
  - '@cspell/cspell-performance-monitor@10.3.3'
  - '@cspell/cspell-pipe@10.3.3'
  - '@cspell/cspell-resolver@10.3.3'
  - '@cspell/cspell-service-bus@10.3.3'
  - '@cspell/cspell-types@10.3.3'
  - '@cspell/cspell-worker@10.3.3'
  - '@cspell/dynamic-import@10.3.3'
  - '@cspell/filetypes@10.3.3'
  - '@cspell/rpc@10.3.3'
  - '@cspell/strong-weak-map@10.3.3'
  - '@cspell/url@10.3.3'
  - '@vercel/cli-auth@0.3.8'
  - '@vercel/cli-config@0.2.7'
  - '@vercel/container@8.2.0'
  - '@vercel/next@12.0.2'
  - '@vercel/vc-native-darwin-arm64@59.19.0'
  - '@vercel/vc-native-darwin-x64@59.19.0'
  - '@vercel/vc-native-linux-arm64@59.19.0'
  - '@vercel/vc-native-linux-x64@59.19.0'
  - cspell-config-lib@10.3.3
  - cspell-dictionary@10.3.3
  - cspell-gitignore@10.3.3
  - cspell-glob@10.3.3
  - cspell-grammar@10.3.3
  - cspell-io@10.3.3
  - cspell-lib@10.3.3
  - cspell-trie-lib@10.3.3
  - cspell@10.3.3
  - prettier@3.9.7
  - vercel@59.19.0
