packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@vercel/backends@0.8.36'
  - '@vercel/build-utils@14.0.5'
  - '@vercel/cervel@0.1.44'
  - '@vercel/cli-auth@0.3.4'
  - '@vercel/detect-agent@1.2.5'
  - '@vercel/elysia@0.1.113'
  - '@vercel/express@0.1.127'
  - '@vercel/fastify@0.1.116'
  - '@vercel/gatsby-plugin-vercel-builder@2.2.39'
  - '@vercel/go@3.11.0'
  - '@vercel/h3@0.1.122'
  - '@vercel/hono@0.2.116'
  - '@vercel/koa@0.1.96'
  - '@vercel/nestjs@0.2.117'
  - '@vercel/node@5.9.9'
  - '@vercel/python-analysis@0.13.2'
  - '@vercel/python@6.56.1'
  - '@vercel/remix-builder@5.9.4'
  - '@vercel/static-build@2.12.5'
  - '@vercel/vc-native-darwin-arm64@58.9.4'
  - '@vercel/vc-native-darwin-x64@58.9.4'
  - '@vercel/vc-native-linux-arm64@58.9.4'
  - '@vercel/vc-native-linux-x64@58.9.4'
  - vercel@58.9.4
